server:
  port: 8093
spring:
  rabbitmq:
    host: localhost
    virtual-host: /
    password: guest
    username: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/web10
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  client:
    local-grpc-server:
      address: "static://127.0.0.1:9090"
      enable-keep-alive: true

